<?php

namespace App\Commands\Database;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

class Backup extends BaseCommand
{
    /**
     * The Command's Group
     *
     * @var string
     */
    protected $group = 'Database';

    /**
     * The Command's Name
     *
     * @var string
     */
    protected $name = 'db:backup';

    /**
     * The Command's Description
     *
     * @var string
     */
    protected $description = 'Dumps the database to a SQL file.';

    /**
     * The Command's Usage
     *
     * @var string
     */
    protected $usage = 'db:backup [filename]';

    /**
     * The Command's Arguments
     *
     * @var array
     */
    protected $arguments = [
        'filename' => 'Optional filename for the backup.',
    ];

    /**
     * The Command's Options
     *
     * @var array
     */
    protected $options = [];

    /**
     * Actually execute a command.
     *
     * @param array $params
     */
    public function run(array $params)
    {
        $filename = array_shift($params);

        if (empty($filename)) {
            $filename = 'backup_' . date('Y-m-d_H-i-s') . '.sql';
        }

        if (pathinfo($filename, PATHINFO_EXTENSION) !== 'sql') {
            $filename .= '.sql';
        }

        $path = WRITEPATH . 'backups/' . $filename;

        CLI::write("Starting database backup...", 'yellow');

        try {
            $this->dumpDatabase($path);
            CLI::write("Database backup saved to: " . $path, 'green');
        } catch (\Exception $e) {
            CLI::error("Backup failed: " . $e->getMessage());
        }
    }

    private function dumpDatabase($path)
    {
        $db = \Config\Database::connect();
        $tables = $db->listTables();

        $handle = fopen($path, 'w');
        if (!$handle) {
            throw new \Exception("Could not open file for writing: $path");
        }

        fwrite($handle, "-- Database Backup: " . date('Y-m-d H:i:s') . PHP_EOL);
        fwrite($handle, "-- Generated by BSCMS Backup Command" . PHP_EOL . PHP_EOL);
        fwrite($handle, "SET FOREIGN_KEY_CHECKS=0;" . PHP_EOL . PHP_EOL);

        foreach ($tables as $table) {
            CLI::write("Backing up table: $table", 'light_gray');

            // 1. Drop Table
            fwrite($handle, "DROP TABLE IF EXISTS `$table`;" . PHP_EOL);

            // 2. Create Table
            $row = $db->query("SHOW CREATE TABLE `$table`")->getRowArray();
            if (isset($row['Create Table'])) {
                fwrite($handle, $row['Create Table'] . ";" . PHP_EOL . PHP_EOL);
            }

            // 3. Insert Data
            $rows = $db->table($table)->get()->getResultArray();
            foreach ($rows as $row) {
                $values = array_map(function ($value) use ($db) {
                    if ($value === null) {
                        return 'NULL';
                    }
                    return $db->escape($value);
                }, $row);

                $sql = "INSERT INTO `$table` (`" . implode('`, `', array_keys($row)) . "`) VALUES (" . implode(', ', $values) . ");" . PHP_EOL;
                fwrite($handle, $sql);
            }
            fwrite($handle, PHP_EOL);
        }

        fwrite($handle, "SET FOREIGN_KEY_CHECKS=1;" . PHP_EOL);
        fclose($handle);
    }
}
